### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by arnowillig** [tuxpoldo/fhem-xbmc#2]
Hi there,

please be aware that the icon you used on fhem-xmbc is not GPLized, but under private copyright. 
It is not the official fhem logo but the logo of FHEMobile 3, which is a iOS-App.
However, I will gladly permit the use of the icon for fhem-xmbc if you put in a visible note in the plugin saying something like "The plugin logo is under copyright by bytefeed.com" or similar.
This should also appear on http://addons.kodi.tv/show/service.fhemcinema/ and other possible sites.
If you don't like to do this, (which is also perfectly okay for me) I would kindly ask you to replace the logo in your project / on sites with some other graphics.

You can contact me via http://bytefeed.com.

Ciao, Arno

**Comment by tuxpoldo** [comment]
Sorry for the late reaction. I wish to thank you for the permission to keep the logo. I added the copyright notice in the plugin and it will appear also on the Kodi-Plugin site as soon as they fetch the new version.

Sorry again!

**Comment by arnowillig** [comment]
No problem! Thanks for the patch (5cbac78). Ciao, Arno
