### ISSUE TITLE
Common Tab - no Actions possible to configure

### ISSUE THREAD

**Issue by Admiraldr** [tuxpoldo/fhem-xbmc#4]
On the Common Tab, there is no possibility to configure any action. 
However on the Daily Tab, all possible Actions are show and working.
![image](https://user-images.githubusercontent.com/31703558/32690243-ff1426ae-c6f3-11e7-90f9-3e7ce30fc3f7.jpeg)
![image](https://user-images.githubusercontent.com/31703558/32690244-ff499be0-c6f3-11e7-9656-525dcb99ac09.jpeg)

**Comment by tuxpoldo** [comment]
Than you for the information. The problem has been fixed. I will publish the pull request today.

**Comment by tuxpoldo** [comment]
Pull request was posted: https://github.com/xbmc/repo-scripts/pull/725
